name: .NET Email Service CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Restore dependencies
      run: dotnet restore EmailService/EmailService.csproj  

    - name: Build
      run: dotnet build EmailService/EmailService.csproj --no-restore  

    
    # Example step to send a test email upon deployment
    - name: Send Test Email
      run: dotnet run --project EmailService/EmailService.csproj -- "Test Email"  
    - name: Send Production Email
      env:
        EMAIL_SERVER: smtp.gmail.com
        EMAIL_PORT: 587
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: dotnet run --project EmailService/EmailService.csproj -- "Real Email"  
