name: .NET Email Service CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo '$DOCKER_PASSWORD' | docker login -u $DOCKER_USER --password-stdin

      - name: Build the Docker image
        run: docker build . -f EmailService/Dockerfile -t $DOCKER_USER/EmailService-image:1.0.0

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_USER/EmailService-image:1.0.0
